version: '2.2'
services:
  chatfiles:
    image: guangzhengli/chatfiles:latest
    container_name: chatfiles
    volumes:
      - ./data/documents:/app/documents
      - ./data/decompress:/app/decompress
    ports:
      - 5000:5000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTPS_PROXY}
      - DEBUG_MODE=￥{DEBUG_MODE}
  chatfiles-ui:
    image: guangzhengli/chatfiles-ui:latest
    container_name: chatfiles-ui
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHAT_FILES_SERVER_HOST=http://chatfiles:5000
      - NEXT_PUBLIC_CHAT_FILES_MAX_SIZE=0
    depends_on:
      - chatfiles